RULE-SET,https://raw.githubusercontent.com/vtgpcmsvgs/surge-config/main/rules/reject/reject.list,REJECT
RULE-SET,https://raw.githubusercontent.com/vtgpcmsvgs/surge-config/main/rules/region/tw/crypto_tw.list,"🇹🇼 台湾-自动选择",no-resolve
RULE-SET,https://raw.githubusercontent.com/vtgpcmsvgs/surge-config/main/rules/region/tw/ai_tw.list,"🇹🇼 台湾-自动选择",no-resolve
RULE-SET,https://raw.githubusercontent.com/vtgpcmsvgs/surge-config/main/rules/proxy/proxy.list,"节点选择",no-resolve
RULE-SET,https://raw.githubusercontent.com/vtgpcmsvgs/surge-config/main/rules/region/hk/domains_to_hk.list,"香港-自动测试",no-resolve
RULE-SET,https://raw.githubusercontent.com/vtgpcmsvgs/surge-config/main/rules/region/jp/domains_to_jp.list,"日本-自动测试",no-resolve
RULE-SET,https://raw.githubusercontent.com/vtgpcmsvgs/surge-config/main/rules/region/tw/domains_to_tw.list,"🇹🇼 台湾-自动选择",no-resolve
